# Generated by Django 4.2.8 on 2024-01-22 10:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_content', ckeditor.fields.RichTextField()),
                ('quote_content', ckeditor.fields.RichTextField()),
                ('footer_content', ckeditor.fields.RichTextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticleContent', to='article.article')),
            ],
        ),
    ]
