# Generated by Django 4.2.8 on 2024-01-23 14:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_content_articlecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontent',
            name='footer_content',
        ),
        migrations.RemoveField(
            model_name='articlecontent',
            name='header_content',
        ),
        migrations.RemoveField(
            model_name='articlecontent',
            name='quote_content',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='article.author'),
        ),
    ]
