# Generated by Django 4.2.8 on 2024-01-23 15:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_articlecontent_footer_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecontent',
            old_name='is_quote',
            new_name='quote_content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
