# Generated by Django 4.2.8 on 2024-01-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_rename_is_quote_articlecontent_quote_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecontent',
            old_name='quote_content',
            new_name='is_quote',
        ),
    ]
