# Generated by Django 4.2.8 on 2024-01-23 15:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_rename_quote_content_articlecontent_is_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontent',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='content_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
