# Generated by Django 4.2.8 on 2024-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_article_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('lIKE', 'LIKE'), ('DISLIKE', 'DISLIKE')], default='lIKE', max_length=10),
        ),
    ]
