# Generated by Django 4.2.8 on 2024-01-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_alter_comment_image_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='article.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='top_level_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
